using System.Text.Json;
using Microsoft.Data.Sqlite;

namespace IISWebDeploy.Services;

public sealed class DeploymentStore
{
    private readonly string _dbPath;
    private readonly object _sync = new();
    public DeploymentStore(IHostEnvironment env)
    {
        _dbPath = PathSafety.ResolvePrivate(env.ContentRootPath, "iisdeploy.sqlite");
        Directory.CreateDirectory(Path.GetDirectoryName(_dbPath)!);
        using var db = Open();
        db.ExecuteNonQuery("CREATE TABLE IF NOT EXISTS SchemaVersion (Version INTEGER NOT NULL)");
        if (Convert.ToInt32(db.ExecuteScalar("SELECT COUNT(*) FROM SchemaVersion")) == 0) db.ExecuteNonQuery("INSERT INTO SchemaVersion VALUES (1)");
        db.ExecuteNonQuery("CREATE TABLE IF NOT EXISTS Sites (Id TEXT PRIMARY KEY, Name TEXT NOT NULL, PhysicalPath TEXT NOT NULL, Bindings TEXT NOT NULL, HealthEndpoint TEXT NOT NULL, IisState TEXT NOT NULL, Health INTEGER NOT NULL, HealthReason TEXT NOT NULL, LastObserved TEXT, Operation INTEGER NOT NULL, ActiveArchive TEXT, SnapshotPath TEXT, StagingPath TEXT, HealthObservation TEXT NOT NULL DEFAULT '')");
        db.ExecuteNonQuery("CREATE TABLE IF NOT EXISTS Archives (Id INTEGER PRIMARY KEY AUTOINCREMENT, SiteId TEXT NOT NULL, Path TEXT NOT NULL, OriginalName TEXT NOT NULL, CreatedUtc TEXT NOT NULL, Successful INTEGER NOT NULL, Active INTEGER NOT NULL)");
        db.ExecuteNonQuery("CREATE TABLE IF NOT EXISTS Observations (SiteId TEXT NOT NULL, ObservedUtc TEXT NOT NULL, Json TEXT NOT NULL)");
        db.ExecuteNonQuery("CREATE TABLE IF NOT EXISTS DeploymentJobs (Id INTEGER PRIMARY KEY AUTOINCREMENT, SiteId TEXT NOT NULL, ArchivePath TEXT NOT NULL, OriginalName TEXT NOT NULL, IsRestore INTEGER NOT NULL, State INTEGER NOT NULL)");
        AddColumn(db, "Sites", "SnapshotPath", "TEXT"); AddColumn(db, "Sites", "StagingPath", "TEXT"); AddColumn(db, "Sites", "HealthObservation", "TEXT NOT NULL DEFAULT ''");
        AddColumn(db, "Sites", "ParentSiteId", "TEXT"); AddColumn(db, "Sites", "ApplicationPath", "TEXT NOT NULL DEFAULT '/' "); AddColumn(db, "Sites", "TargetKind", "INTEGER NOT NULL DEFAULT 0"); AddColumn(db, "Sites", "TargetAvailable", "INTEGER NOT NULL DEFAULT 1");
        AddColumn(db, "DeploymentJobs", "ParentSiteId", "TEXT");
        db.ExecuteNonQuery("UPDATE Sites SET ParentSiteId=Id WHERE ParentSiteId IS NULL OR ParentSiteId=''");
        db.ExecuteNonQuery("UPDATE Sites SET ApplicationPath='/', TargetKind=0, TargetAvailable=1 WHERE ApplicationPath IS NULL OR ApplicationPath=''");
        db.ExecuteNonQuery("UPDATE DeploymentJobs SET ParentSiteId=(SELECT ParentSiteId FROM Sites WHERE Sites.Id=DeploymentJobs.SiteId) WHERE ParentSiteId IS NULL OR ParentSiteId=''");
        db.ExecuteNonQuery("CREATE TABLE IF NOT EXISTS ParentReservations (ParentSiteId TEXT PRIMARY KEY, TargetId TEXT NOT NULL, JobId INTEGER NOT NULL, Operation TEXT NOT NULL, AcquiredUtc TEXT NOT NULL, Status TEXT NOT NULL)");
    }
    private static void AddColumn(SqliteConnection db, string table, string column, string type) { try { db.ExecuteNonQuery($"ALTER TABLE {table} ADD COLUMN {column} {type}"); } catch (SqliteException ex) when (ex.SqliteErrorCode == 1) { } }
    private SqliteConnection Open() { var c = new SqliteConnection($"Data Source={_dbPath};Mode=ReadWriteCreate;Cache=Private"); c.Open(); return c; }
    private const string SiteColumns = "Id,Name,ParentSiteId,ApplicationPath,TargetKind,TargetAvailable,PhysicalPath,Bindings,HealthEndpoint,IisState,Health,HealthReason,LastObserved,Operation,ActiveArchive,SnapshotPath,StagingPath,HealthObservation";
    public SiteRecord? Site(string id) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = $"SELECT {SiteColumns} FROM Sites WHERE Id=$id"; cmd.Parameters.AddWithValue("$id", id); using var r = cmd.ExecuteReader(); return r.Read() ? ReadSite(r) : null; } }
    public IReadOnlyList<SiteRecord> Sites()
    { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = $"SELECT {SiteColumns} FROM Sites ORDER BY Name,ApplicationPath"; using var r = cmd.ExecuteReader(); var result = new List<SiteRecord>(); while (r.Read()) result.Add(ReadSite(r)); return result; } }
    private static SiteRecord ReadSite(SqliteDataReader r) => new() { Id = r.GetString(0), Name = r.GetString(1), ParentSiteId = r.IsDBNull(2) ? r.GetString(0) : r.GetString(2), ApplicationPath = ApplicationTargetIdentity.NormalizePath(r.IsDBNull(3) ? "/" : r.GetString(3)), TargetKind = (TargetKind)r.GetInt32(4), TargetAvailable = r.GetInt32(5) != 0, PhysicalPath = r.GetString(6), BindingsJson = r.GetString(7), HealthEndpoint = r.GetString(8), IisState = r.GetString(9), Health = (HealthTier)r.GetInt32(10), HealthReason = r.GetString(11), LastObservedUtc = r.IsDBNull(12) ? null : DateTimeOffset.Parse(r.GetString(12)), Operation = (OperationPhase)r.GetInt32(13), ActiveArchive = r.IsDBNull(14) ? null : r.GetString(14), SnapshotPath = r.IsDBNull(15) ? null : r.GetString(15), StagingPath = r.IsDBNull(16) ? null : r.GetString(16), HealthObservationJson = r.IsDBNull(17) ? "" : r.GetString(17) };
    public void Upsert(SiteRecord s) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "INSERT INTO Sites (Id,Name,ParentSiteId,ApplicationPath,TargetKind,TargetAvailable,PhysicalPath,Bindings,HealthEndpoint,IisState,Health,HealthReason,LastObserved,Operation,ActiveArchive,SnapshotPath,StagingPath,HealthObservation) VALUES ($id,$name,$parent,$app,$kind,$available,$path,$bindings,$endpoint,$state,$health,$reason,$observed,$operation,$active,$snapshot,$staging,$observation) ON CONFLICT(Id) DO UPDATE SET Name=$name,ParentSiteId=$parent,ApplicationPath=$app,TargetKind=$kind,TargetAvailable=$available,PhysicalPath=$path,Bindings=$bindings,HealthEndpoint=$endpoint,IisState=$state,Health=$health,HealthReason=$reason,LastObserved=$observed,Operation=$operation,ActiveArchive=$active,SnapshotPath=$snapshot,StagingPath=$staging,HealthObservation=$observation"; AddSiteParameters(cmd, s); cmd.ExecuteNonQuery(); } }
    public void UpdateDiscovery(SiteRecord s, string? reason = null) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "INSERT INTO Sites (Id,Name,ParentSiteId,ApplicationPath,TargetKind,TargetAvailable,PhysicalPath,Bindings,HealthEndpoint,IisState,Health,HealthReason,LastObserved,Operation,ActiveArchive,SnapshotPath,StagingPath,HealthObservation) VALUES ($id,$name,$parent,$app,$kind,$available,$path,$bindings,$endpoint,$state,$health,$insertReason,$observed,$operation,$active,$snapshot,$staging,$observation) ON CONFLICT(Id) DO UPDATE SET Name=$name,ParentSiteId=$parent,ApplicationPath=$app,TargetKind=$kind,TargetAvailable=$available,PhysicalPath=$path,Bindings=$bindings,IisState=$state,HealthReason=CASE WHEN Operation=$recovery THEN HealthReason ELSE COALESCE($reason,HealthReason) END"; cmd.Parameters.AddWithValue("$id", s.Id); cmd.Parameters.AddWithValue("$name", s.Name); cmd.Parameters.AddWithValue("$parent", string.IsNullOrWhiteSpace(s.ParentSiteId) ? s.Id : s.ParentSiteId); cmd.Parameters.AddWithValue("$app", ApplicationTargetIdentity.NormalizePath(s.ApplicationPath)); cmd.Parameters.AddWithValue("$kind", (int)s.TargetKind); cmd.Parameters.AddWithValue("$available", s.TargetAvailable ? 1 : 0); cmd.Parameters.AddWithValue("$path", s.PhysicalPath); cmd.Parameters.AddWithValue("$bindings", s.BindingsJson); cmd.Parameters.AddWithValue("$endpoint", s.HealthEndpoint); cmd.Parameters.AddWithValue("$state", s.IisState); cmd.Parameters.AddWithValue("$health", (int)s.Health); cmd.Parameters.AddWithValue("$insertReason", s.HealthReason); cmd.Parameters.AddWithValue("$reason", (object?)reason ?? DBNull.Value); cmd.Parameters.AddWithValue("$observed", (object?)s.LastObservedUtc?.ToString("O") ?? DBNull.Value); cmd.Parameters.AddWithValue("$operation", (int)s.Operation); cmd.Parameters.AddWithValue("$active", (object?)s.ActiveArchive ?? DBNull.Value); cmd.Parameters.AddWithValue("$snapshot", (object?)s.SnapshotPath ?? DBNull.Value); cmd.Parameters.AddWithValue("$staging", (object?)s.StagingPath ?? DBNull.Value); cmd.Parameters.AddWithValue("$observation", s.HealthObservationJson); cmd.Parameters.AddWithValue("$recovery", (int)OperationPhase.RecoveryRequired); cmd.ExecuteNonQuery(); } }
    public void UpdateHealth(string siteId, HealthObservation o) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "UPDATE Sites SET Health=$health,HealthReason=CASE WHEN Operation=$recovery THEN HealthReason ELSE $reason END,LastObserved=$observed,HealthObservation=$observation WHERE Id=$id"; cmd.Parameters.AddWithValue("$id", siteId); cmd.Parameters.AddWithValue("$health", (int)o.Overall); cmd.Parameters.AddWithValue("$reason", o.Reason); cmd.Parameters.AddWithValue("$observed", o.ObservedUtc.ToString("O")); cmd.Parameters.AddWithValue("$observation", JsonSerializer.Serialize(o, JsonDefaults.Web)); cmd.Parameters.AddWithValue("$recovery", (int)OperationPhase.RecoveryRequired); cmd.ExecuteNonQuery(); } }
    public void UpdateIisState(string siteId, string state) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "UPDATE Sites SET IisState=$state WHERE Id=$id"; cmd.Parameters.AddWithValue("$id", siteId); cmd.Parameters.AddWithValue("$state", state); cmd.ExecuteNonQuery(); } }
    public void UpdateEndpoint(string siteId, string endpoint) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "UPDATE Sites SET HealthEndpoint=$endpoint WHERE Id=$id AND Operation NOT IN ($staging,$snapshot,$quiescing,$deploying,$verifying,$restoring)"; cmd.Parameters.AddWithValue("$id", siteId); cmd.Parameters.AddWithValue("$endpoint", endpoint); foreach (var phase in new[] { OperationPhase.Staging, OperationPhase.Snapshot, OperationPhase.Quiescing, OperationPhase.Deploying, OperationPhase.Verifying, OperationPhase.Restoring }) cmd.Parameters.AddWithValue("$" + phase.ToString().ToLowerInvariant(), (int)phase); if (cmd.ExecuteNonQuery() != 1) throw new InvalidOperationException("Healthcheck endpoint cannot be changed during an active deployment."); } }
    public void UpdateOperation(SiteRecord s) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "UPDATE Sites SET Operation=$operation,ActiveArchive=$active,SnapshotPath=$snapshot,StagingPath=$staging,HealthReason=$reason WHERE Id=$id"; cmd.Parameters.AddWithValue("$id", s.Id); cmd.Parameters.AddWithValue("$operation", (int)s.Operation); cmd.Parameters.AddWithValue("$active", (object?)s.ActiveArchive ?? DBNull.Value); cmd.Parameters.AddWithValue("$snapshot", (object?)s.SnapshotPath ?? DBNull.Value); cmd.Parameters.AddWithValue("$staging", (object?)s.StagingPath ?? DBNull.Value); cmd.Parameters.AddWithValue("$reason", s.HealthReason); cmd.ExecuteNonQuery(); } }
    public void SetRecoveryIfActive(string siteId) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "UPDATE Sites SET Operation=$recovery,HealthReason='The process restarted during deployment. Manual recovery is required; no automatic file mutation was attempted.' WHERE Id=$id AND Operation NOT IN ($none,$completed,$failed,$recoveryPhase) AND NOT EXISTS (SELECT 1 FROM DeploymentJobs WHERE SiteId=$id AND State=$completedJob)"; cmd.Parameters.AddWithValue("$id", siteId); cmd.Parameters.AddWithValue("$recovery", (int)OperationPhase.RecoveryRequired); cmd.Parameters.AddWithValue("$none", (int)OperationPhase.None); cmd.Parameters.AddWithValue("$completed", (int)OperationPhase.Completed); cmd.Parameters.AddWithValue("$failed", (int)OperationPhase.Failed); cmd.Parameters.AddWithValue("$recoveryPhase", (int)OperationPhase.RecoveryRequired); cmd.Parameters.AddWithValue("$completedJob", (int)DeploymentJobState.Completed); cmd.ExecuteNonQuery(); } }
    private static void AddSiteParameters(SqliteCommand cmd, SiteRecord s) { cmd.Parameters.AddWithValue("$id", s.Id); cmd.Parameters.AddWithValue("$name", s.Name); cmd.Parameters.AddWithValue("$parent", string.IsNullOrWhiteSpace(s.ParentSiteId) ? s.Id : s.ParentSiteId); cmd.Parameters.AddWithValue("$app", ApplicationTargetIdentity.NormalizePath(s.ApplicationPath)); cmd.Parameters.AddWithValue("$kind", (int)s.TargetKind); cmd.Parameters.AddWithValue("$available", s.TargetAvailable ? 1 : 0); cmd.Parameters.AddWithValue("$path", s.PhysicalPath); cmd.Parameters.AddWithValue("$bindings", s.BindingsJson); cmd.Parameters.AddWithValue("$endpoint", s.HealthEndpoint); cmd.Parameters.AddWithValue("$state", s.IisState); cmd.Parameters.AddWithValue("$health", (int)s.Health); cmd.Parameters.AddWithValue("$reason", s.HealthReason); cmd.Parameters.AddWithValue("$observed", (object?)s.LastObservedUtc?.ToString("O") ?? DBNull.Value); cmd.Parameters.AddWithValue("$operation", (int)s.Operation); cmd.Parameters.AddWithValue("$active", (object?)s.ActiveArchive ?? DBNull.Value); cmd.Parameters.AddWithValue("$snapshot", (object?)s.SnapshotPath ?? DBNull.Value); cmd.Parameters.AddWithValue("$staging", (object?)s.StagingPath ?? DBNull.Value); cmd.Parameters.AddWithValue("$observation", s.HealthObservationJson); }
    public void SaveObservation(string siteId, HealthObservation o) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "INSERT INTO Observations VALUES ($id,$time,$json)"; cmd.Parameters.AddWithValue("$id", siteId); cmd.Parameters.AddWithValue("$time", o.ObservedUtc.ToString("O")); cmd.Parameters.AddWithValue("$json", JsonSerializer.Serialize(o, JsonDefaults.Web)); cmd.ExecuteNonQuery(); } }
    public long AddArchive(ArchiveRecord a) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "INSERT INTO Archives (SiteId,Path,OriginalName,CreatedUtc,Successful,Active) VALUES ($site,$path,$name,$created,$success,$active); SELECT last_insert_rowid();"; AddArchiveParameters(cmd, a); return (long)cmd.ExecuteScalar()!; } }
    private static void AddArchiveParameters(SqliteCommand cmd, ArchiveRecord a) { cmd.Parameters.AddWithValue("$site", a.SiteId); cmd.Parameters.AddWithValue("$path", a.Path); cmd.Parameters.AddWithValue("$name", a.OriginalName); cmd.Parameters.AddWithValue("$created", a.CreatedUtc.ToString("O")); cmd.Parameters.AddWithValue("$success", a.Successful ? 1 : 0); cmd.Parameters.AddWithValue("$active", a.Active ? 1 : 0); }
    public void SetActive(string siteId, string path) { lock (_sync) { using var db = Open(); using var tx = db.BeginTransaction(); using var clear = db.CreateCommand(); clear.Transaction = tx; clear.CommandText = "UPDATE Archives SET Active=0 WHERE SiteId=$site"; clear.Parameters.AddWithValue("$site", siteId); clear.ExecuteNonQuery(); using var set = db.CreateCommand(); set.Transaction = tx; set.CommandText = "UPDATE Archives SET Active=1 WHERE SiteId=$site AND Path=$path AND Successful=1"; set.Parameters.AddWithValue("$site", siteId); set.Parameters.AddWithValue("$path", path); set.ExecuteNonQuery(); tx.Commit(); } }
    public IReadOnlyList<ArchiveRecord> Archives(string siteId) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "SELECT Id,SiteId,Path,OriginalName,CreatedUtc,Successful,Active FROM Archives WHERE SiteId=$site AND Successful=1 ORDER BY CreatedUtc DESC"; cmd.Parameters.AddWithValue("$site", siteId); using var r = cmd.ExecuteReader(); var result = new List<ArchiveRecord>(); while (r.Read()) result.Add(new ArchiveRecord { Id = r.GetInt64(0), SiteId = r.GetString(1), Path = r.GetString(2), OriginalName = r.GetString(3), CreatedUtc = DateTimeOffset.Parse(r.GetString(4)), Successful = r.GetInt32(5) != 0, Active = r.GetInt32(6) != 0 }); return result; } }
    public ArchiveRecord? Archive(long id) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "SELECT Id,SiteId,Path,OriginalName,CreatedUtc,Successful,Active FROM Archives WHERE Id=$id"; cmd.Parameters.AddWithValue("$id", id); using var r = cmd.ExecuteReader(); return r.Read() ? new ArchiveRecord { Id = r.GetInt64(0), SiteId = r.GetString(1), Path = r.GetString(2), OriginalName = r.GetString(3), CreatedUtc = DateTimeOffset.Parse(r.GetString(4)), Successful = r.GetInt32(5) != 0, Active = r.GetInt32(6) != 0 } : null; } }
    public void Retain(string siteId, int count) { lock (_sync) { using var db = Open(); using var cmd = db.CreateCommand(); cmd.CommandText = "SELECT Id,Path FROM Archives WHERE SiteId=$site AND Successful=1 AND Active=0 ORDER BY CreatedUtc DESC"; cmd.Parameters.AddWithValue("$site", siteId); using var r = cmd.ExecuteReader(); var remove = new List<(long, string)>(); var index = 0; while (r.Read()) if (++index > Math.Max(0, count - 1)) remove.Add((r.GetInt64(0), r.GetString(1))); r.Close(); foreach (var item in remove) { if (File.Exists(item.Item2)) File.Delete(item.Item2); using var del = db.CreateCommand(); del.CommandText = "DELETE FROM Archives WHERE Id=$id"; del.Parameters.AddWithValue("$id", item.Item1); del.ExecuteNonQuery(); } } }
    public IReadOnlyList<ParentReservation> Reservations()
    {
        lock (_sync)
        {
            using var db = Open(); using var cmd = db.CreateCommand();
            cmd.CommandText = "SELECT ParentSiteId,TargetId,JobId,Operation,AcquiredUtc,Status FROM ParentReservations";
            using var r = cmd.ExecuteReader(); var result = new List<ParentReservation>();
            while (r.Read()) result.Add(new ParentReservation { ParentSiteId = r.GetString(0), TargetId = r.GetString(1), JobId = r.GetInt64(2), Operation = r.GetString(3), AcquiredUtc = DateTimeOffset.Parse(r.GetString(4)), Status = r.GetString(5) });
            return result;
        }
    }

    public bool TryEnqueue(DeploymentJob job)
    {
        lock (_sync)
        {
            using var db = Open(); using var tx = db.BeginTransaction();
            using var check = db.CreateCommand(); check.Transaction = tx; check.CommandText = "SELECT Operation,ParentSiteId,TargetAvailable FROM Sites WHERE Id=$site"; check.Parameters.AddWithValue("$site", job.SiteId); using var target = check.ExecuteReader(); if (!target.Read() || !target.GetBoolean(2)) return false; var operation = target.GetInt32(0); job.ParentSiteId = target.IsDBNull(1) ? job.SiteId : target.GetString(1); target.Close();
            if ((OperationPhase)operation is not (OperationPhase.None or OperationPhase.Completed or OperationPhase.Failed)) return false;
            using var insert = db.CreateCommand(); insert.Transaction = tx; insert.CommandText = "INSERT INTO DeploymentJobs (SiteId,ParentSiteId,ArchivePath,OriginalName,IsRestore,State) VALUES ($site,$parent,$path,$name,$restore,$state); SELECT last_insert_rowid();";
            insert.Parameters.AddWithValue("$site", job.SiteId); insert.Parameters.AddWithValue("$parent", job.ParentSiteId); insert.Parameters.AddWithValue("$path", job.ArchivePath); insert.Parameters.AddWithValue("$name", job.OriginalName); insert.Parameters.AddWithValue("$restore", job.IsRestore ? 1 : 0); insert.Parameters.AddWithValue("$state", (int)DeploymentJobState.Pending); job.Id = (long)insert.ExecuteScalar()!;
            using var reserve = db.CreateCommand(); reserve.Transaction = tx; reserve.CommandText = "INSERT INTO ParentReservations (ParentSiteId,TargetId,JobId,Operation,AcquiredUtc,Status) VALUES ($parent,$target,$job,$operation,$time,'Pending')"; reserve.Parameters.AddWithValue("$parent", job.ParentSiteId); reserve.Parameters.AddWithValue("$target", job.SiteId); reserve.Parameters.AddWithValue("$job", job.Id); reserve.Parameters.AddWithValue("$operation", job.IsRestore ? "restore" : "deploy"); reserve.Parameters.AddWithValue("$time", DateTimeOffset.UtcNow.ToString("O")); try { reserve.ExecuteNonQuery(); } catch (SqliteException ex) when (ex.SqliteErrorCode == 19) { return false; }
            using var update = db.CreateCommand(); update.Transaction = tx; update.CommandText = "UPDATE Sites SET Operation=$operation,HealthReason=$reason WHERE Id=$site"; update.Parameters.AddWithValue("$operation", (int)OperationPhase.Staging); update.Parameters.AddWithValue("$reason", "Upload staged; deployment queued on the server."); update.Parameters.AddWithValue("$site", job.SiteId); update.ExecuteNonQuery(); tx.Commit(); return true;
        }
    }
    public DeploymentJob? ClaimNextJob()
    {
        lock (_sync) { using var db = Open(); using var tx = db.BeginTransaction(); using var find = db.CreateCommand(); find.Transaction = tx; find.CommandText = "SELECT Id,SiteId,ParentSiteId,ArchivePath,OriginalName,IsRestore FROM DeploymentJobs WHERE State=$state ORDER BY Id LIMIT 1"; find.Parameters.AddWithValue("$state", (int)DeploymentJobState.Pending); using var r = find.ExecuteReader(); if (!r.Read()) return null; var job = new DeploymentJob { Id = r.GetInt64(0), SiteId = r.GetString(1), ParentSiteId = r.GetString(2), ArchivePath = r.GetString(3), OriginalName = r.GetString(4), IsRestore = r.GetInt32(5) != 0, State = DeploymentJobState.Running }; r.Close(); using var claim = db.CreateCommand(); claim.Transaction = tx; claim.CommandText = "UPDATE DeploymentJobs SET State=$running WHERE Id=$id"; claim.Parameters.AddWithValue("$running", (int)DeploymentJobState.Running); claim.Parameters.AddWithValue("$id", job.Id); claim.ExecuteNonQuery(); using var reserve = db.CreateCommand(); reserve.Transaction = tx; reserve.CommandText = "UPDATE ParentReservations SET Status='Running',JobId=$id WHERE ParentSiteId=$parent"; reserve.Parameters.AddWithValue("$id", job.Id); reserve.Parameters.AddWithValue("$parent", job.ParentSiteId); reserve.ExecuteNonQuery(); tx.Commit(); return job; }
    }
    public void CompleteJob(long id, bool success, bool releaseRecoveryReservation = false) { lock (_sync) { using var db = Open(); using var tx = db.BeginTransaction(); string? parent; string? site; using (var find = db.CreateCommand()) { find.Transaction = tx; find.CommandText = "SELECT ParentSiteId,SiteId FROM DeploymentJobs WHERE Id=$id"; find.Parameters.AddWithValue("$id", id); using var r = find.ExecuteReader(); if (!r.Read()) return; parent = r.GetString(0); site = r.GetString(1); } using (var cmd = db.CreateCommand()) { cmd.Transaction = tx; cmd.CommandText = "UPDATE DeploymentJobs SET State=$state WHERE Id=$id"; cmd.Parameters.AddWithValue("$state", (int)(success ? DeploymentJobState.Completed : DeploymentJobState.Failed)); cmd.Parameters.AddWithValue("$id", id); cmd.ExecuteNonQuery(); } using var state = db.CreateCommand(); state.Transaction = tx; state.CommandText = "SELECT Operation FROM Sites WHERE Id=$site"; state.Parameters.AddWithValue("$site", site); var phase = state.ExecuteScalar(); if (!success && phase is not null && (OperationPhase)Convert.ToInt32(phase) is not (OperationPhase.None or OperationPhase.Staging or OperationPhase.Completed or OperationPhase.Failed or OperationPhase.RecoveryRequired)) { using var recover = db.CreateCommand(); recover.Transaction = tx; recover.CommandText = "UPDATE Sites SET Operation=$recovery,HealthReason='Deployment worker stopped before rollback completed; manual recovery is required.' WHERE Id=$site"; recover.Parameters.AddWithValue("$recovery", (int)OperationPhase.RecoveryRequired); recover.Parameters.AddWithValue("$site", site); recover.ExecuteNonQuery(); phase = (int)OperationPhase.RecoveryRequired; } if (phase is not null && (OperationPhase)Convert.ToInt32(phase) == OperationPhase.Staging) { using var finalize = db.CreateCommand(); finalize.Transaction = tx; finalize.CommandText = "UPDATE Sites SET Operation=$phase,HealthReason=$reason,StagingPath=NULL,SnapshotPath=NULL WHERE Id=$site"; finalize.Parameters.AddWithValue("$phase", (int)(success ? OperationPhase.Completed : OperationPhase.Failed)); finalize.Parameters.AddWithValue("$reason", success ? "Deployment completed." : "Deployment failed before file mutation."); finalize.Parameters.AddWithValue("$site", site); finalize.ExecuteNonQuery(); } if (parent is not null && phase is not null && ((OperationPhase)Convert.ToInt32(phase) != OperationPhase.RecoveryRequired || releaseRecoveryReservation)) { using var release = db.CreateCommand(); release.Transaction = tx; release.CommandText = "DELETE FROM ParentReservations WHERE ParentSiteId=$parent AND JobId=$id"; release.Parameters.AddWithValue("$parent", parent); release.Parameters.AddWithValue("$id", id); release.ExecuteNonQuery(); } tx.Commit(); } }
    public bool AcknowledgeRecovery(string siteId, string parentSiteId) { lock (_sync) { using var db = Open(); using var tx = db.BeginTransaction(); string? snapshot; string? staging; using (var site = db.CreateCommand()) { site.Transaction = tx; site.CommandText = "SELECT Operation,ParentSiteId,SnapshotPath,StagingPath FROM Sites WHERE Id=$id"; site.Parameters.AddWithValue("$id", siteId); using var r = site.ExecuteReader(); if (!r.Read() || (OperationPhase)r.GetInt32(0) != OperationPhase.RecoveryRequired || r.GetString(1) != parentSiteId || r.IsDBNull(2) || r.IsDBNull(3)) return false; snapshot = r.GetString(2); staging = r.GetString(3); } if (!Directory.Exists(snapshot) || !Directory.Exists(staging)) return false; using var active = db.CreateCommand(); active.Transaction = tx; active.CommandText = "SELECT COUNT(*) FROM DeploymentJobs WHERE ParentSiteId=$parent AND State IN ($pending,$running)"; active.Parameters.AddWithValue("$parent", parentSiteId); active.Parameters.AddWithValue("$pending", (int)DeploymentJobState.Pending); active.Parameters.AddWithValue("$running", (int)DeploymentJobState.Running); if (Convert.ToInt32(active.ExecuteScalar()) != 0) return false; using var reservation = db.CreateCommand(); reservation.Transaction = tx; reservation.CommandText = "SELECT COUNT(*) FROM ParentReservations WHERE ParentSiteId=$parent AND TargetId=$target AND Status='RecoveryRequired'"; reservation.Parameters.AddWithValue("$parent", parentSiteId); reservation.Parameters.AddWithValue("$target", siteId); if (Convert.ToInt32(reservation.ExecuteScalar()) != 1) return false; using var clear = db.CreateCommand(); clear.Transaction = tx; clear.CommandText = "UPDATE Sites SET Operation=$none,HealthReason='Recovery evidence acknowledged by operator; deployment is permitted.' WHERE Id=$id AND Operation=$recovery"; clear.Parameters.AddWithValue("$none", (int)OperationPhase.None); clear.Parameters.AddWithValue("$recovery", (int)OperationPhase.RecoveryRequired); clear.Parameters.AddWithValue("$id", siteId); if (clear.ExecuteNonQuery() != 1) return false; using var release = db.CreateCommand(); release.Transaction = tx; release.CommandText = "DELETE FROM ParentReservations WHERE ParentSiteId=$parent AND TargetId=$target AND Status='RecoveryRequired'"; release.Parameters.AddWithValue("$parent", parentSiteId); release.Parameters.AddWithValue("$target", siteId); release.ExecuteNonQuery(); tx.Commit(); return true; } }
    public void MarkRunningJobsForRecovery() { lock (_sync) { using var db = Open(); using var tx = db.BeginTransaction(); using var cmd = db.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "UPDATE Sites SET Operation=$recovery,HealthReason='The process stopped during deployment; manual recovery is required.' WHERE Id IN (SELECT SiteId FROM DeploymentJobs WHERE State=$running) AND Operation NOT IN ($completed,$failed,$recoveryPhase)"; cmd.Parameters.AddWithValue("$recovery", (int)OperationPhase.RecoveryRequired); cmd.Parameters.AddWithValue("$running", (int)DeploymentJobState.Running); cmd.Parameters.AddWithValue("$completed", (int)OperationPhase.Completed); cmd.Parameters.AddWithValue("$failed", (int)OperationPhase.Failed); cmd.Parameters.AddWithValue("$recoveryPhase", (int)OperationPhase.RecoveryRequired); cmd.ExecuteNonQuery(); using var reservation = db.CreateCommand(); reservation.Transaction = tx; reservation.CommandText = "UPDATE ParentReservations SET Status='RecoveryRequired' WHERE JobId IN (SELECT Id FROM DeploymentJobs WHERE State=$running)"; reservation.Parameters.AddWithValue("$running", (int)DeploymentJobState.Running); reservation.ExecuteNonQuery(); tx.Commit(); } }
}
internal static class SqliteExtensions { public static void ExecuteNonQuery(this SqliteConnection db, string sql) { using var cmd = db.CreateCommand(); cmd.CommandText = sql; cmd.ExecuteNonQuery(); } public static object? ExecuteScalar(this SqliteConnection db, string sql) { using var cmd = db.CreateCommand(); cmd.CommandText = sql; return cmd.ExecuteScalar(); } }
